
1. Vectores y matrices


```{r}

student1 = c(50.4,62.3,92.1,77.6,TRUE)
student2 = c(41.7,87.9,75.3,72.4,FALSE)
student3 = c(30.3,67.8,69.3,71.2,FALSE)
student4 = c(65.4,85.1,92.3,96.8,TRUE)
student5 = c(70.4,88.2,95.2,90.7,TRUE)

students_vector=c(student1,student2,student3,student4,student5)

matrix(students_vector,ncol = 5,nrow = 5, byrow = TRUE)
students_matriz = matrix(students_vector,ncol = 5,nrow = 5, byrow = TRUE)
```
2. Nombrado de una matriz



```{r}

name_students = c("Lily Brown","Davis Moore","Susan Taylor", "Mike Jones", "Tom Hill")
name_courses_legal_age = c("TIC" , "Accounting", "Psychology", "Ethics","Legal_age")
colnames(students_matriz) <-  name_courses_legal_age
rownames(students_matriz) <- name_students
students_matriz


```

3. rowSums, cbind

```{r}

total_grade_student= rowSums(students_matriz[,1:4])

total_grade_student





```
rowSums(students_matriz[,1:4])

```{r}


result_students = cbind(total_grade_student,students_matriz)

result_students

```





4. Seleccionando elementos de una matriz

```{r}

selected_elements = result_students[c(1,3,5),c(2,4)]

selected_elements

```

5. Data frames

```{r}
students_grades_df = as.data.frame(result_students)

students_grades_df







```
5.2

```{r}
subset(students_grades_df,subset =Accounting>80)



```



```{r}
subset(students_grades_df,subset =Accounting>80 & Legal_age==1)




```

6. Funciones, Condicionales y Bucles


```{r}

students_projection <- function(x,y){
  
  a=result_students
  
  
}



```






7. Data frames y lapply

7.1
```{r}

index_education = function(grande){
  (1+(grande/100))/2
}
index_education(10)





```
7.2

```{r}
students_grades_df


all_students_grade= students_grades_df[c(1:5),c(2:5)]

all_students_grade

```

7.3


```{r}
lapply(all_students_grade,index_education)




```









8. Math utilities
```{r}


score_mean = rowMeans(students_grades_df[c(2,3,4,5)],na.rm = TRUE)

score_mean
```







